# Generated by Django 3.1.5 on 2021-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_actor', models.CharField(max_length=200)),
                ('movie_actress', models.CharField(max_length=200)),
                ('movie_director', models.CharField(max_length=200)),
                ('movie_production', models.CharField(max_length=200)),
                ('movie_release_date', models.DateField()),
                ('movie_poster', models.ImageField(upload_to='static/images/movieposter')),
            ],
        ),
    ]
